mainbuild.py: ./constants.py \
  ./devices.py \
  ./util.py \
  ./preprocessor.py \
  ./main.py 
	python preprocessor.py main.py --build-file=mainbuild.py
Makefile.depends: $(filter $(shell find -name "*.py" -not -path "./.*"),./constants.py \
  ./devices.py \
  ./util.py \
  ./preprocessor.py \
  ./main.py )
	python preprocessor.py main.py --dependency-file=Makefile.depends --build-file=mainbuild.py
